// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/junpayment/ollamaproxy/config"
	"github.com/junpayment/ollamaproxy/handlers"
	"github.com/junpayment/ollamaproxy/infrastructures"
)

// Injectors from injector.go:

func InitAPI() *API {
	modelsConfig := config.NewConfig()
	openAIClient := infrastructures.NewOpenAIClient(modelsConfig)
	handlersHandlers := handlers.NewHandlers(openAIClient)
	api := newAPI(handlersHandlers)
	return api
}
